# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Tim Finkel
tagline:             Insignificant Digits
description:         'I''m a data guy. These are my thoughts.'
url:                 http://timfinkel.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Tim Finkel
  url:               https://twitter.com/king_fink
  email:             tim.finkel@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate_path: "page:num"

# Top-nav
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Social
social_list:
  Twitter: 'http://twitter.com/king_fink'
  LinkedIn: 'http://linkedin.com/in/timfinkel'
  GitHub: 'http://github.com/king_fink'
