# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Tim Finkel
tagline:             'A data guy'
description:         'A data guy. <a href="https://twitter.com/king_fink" target="_blank">@king_fink</a>.'
url:                 http://timfinkel.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tim Finkel
  url:               https://twitter.com/king_fink
  email:             tim.finkel@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate_path: "page:num"

# Top-nav
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
